on:
  push:
    tags:  #only trigger action when tagged with release number, i.e v0.0.1     
      - 'v*'    
  workflow_dispatch:

name: Publish Rust crate to crates.io

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Get git tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo install cargo-edit
      - name: Release details
        run: echo Release tag ${{ steps.tag.outputs.tag }}
      - run: TAG=${{ github.event.release.tag_name }}
      - run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - run: echo Version is $VERSION
      - run: cargo set-version $VERSION
        working-directory: ./ledger-models-rust
      - run: cargo publish --token ${CRATES_TOKEN}
        working-directory: ./ledger-models-rust
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
