name: Publish Rust crate to crates.io

on:
  push:
    tags:  #only trigger action when tagged with release number, i.e v0.0.1     
      - 'v*'    
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ledger-models-rust

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Get git tag extension
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Release details
        run: |
          echo Release tag ${{ steps.tag.outputs.tag }}
          TAG=${{ steps.tag.outputs.tag }}
          echo tag is ${TAG}
          VERSION=${TAG#v}
          echo version is ${VERSION}
          echo "release_version=${VERSION}" >> $GITHUB_ENV
      - run: |
          cargo install cargo-edit
          cargo set-version ${{ env.release_version }}
          cargo publish --token ${CRATES_TOKEN} --allow-dirty
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
