name: Publish JS package to GitHub Packages
on:
  push:
    tags:  #only trigger action when tagged with release number, i.e v0.0.1     
      - 'v*'    
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ledger-models-javascript
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      - name: Get git tag extension
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Release details
        run: |
          echo Release tag ${{ steps.tag.outputs.tag }}
          TAG=${{ steps.tag.outputs.tag }}
          echo tag is ${TAG}
          VERSION=${TAG#v}
          echo version is ${VERSION}
          echo "release_version=${VERSION}" >> $GITHUB_ENV
      - name: Print Environment Variables
        run: env
      - run: |
          echo "@username:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          cat .nprmc
          npm ci
          echo ${{ env.release_version }} 
          npm version ${{ env.release_version }} 
          npm publish
 
